# Generated by Django 4.2 on 2023-07-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('nid', models.IntegerField()),
                ('vid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('clid', models.IntegerField()),
                ('tid', models.IntegerField()),
            ],
            options={
                'db_table': 'idgen',
            },
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('not_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('not_athority', models.CharField(max_length=100)),
                ('not_data', models.CharField(max_length=200)),
                ('not_date', models.CharField(max_length=100)),
                ('not_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='tbl_organization',
            fields=[
                ('org_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_city', models.CharField(max_length=100)),
                ('org_location', models.CharField(max_length=100)),
                ('org_phone', models.CharField(max_length=100)),
                ('org_email', models.CharField(max_length=100)),
                ('org_category', models.CharField(max_length=100)),
                ('org_contact_person_name', models.CharField(max_length=100)),
                ('org_license_no', models.CharField(max_length=100)),
                ('org_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_organization',
            },
        ),
        migrations.CreateModel(
            name='tbl_visitor',
            fields=[
                ('vis_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vis_name', models.CharField(max_length=100)),
                ('vis_phone', models.CharField(max_length=100)),
                ('vis_email', models.CharField(max_length=100)),
                ('vis_date', models.CharField(max_length=100)),
                ('vis_time', models.CharField(max_length=100)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_organization')),
            ],
            options={
                'db_table': 'tbl_visitor',
            },
        ),
    ]
