# Generated by Django 4.2 on 2023-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_idgen_tbl_notification_tbl_organization_tbl_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('comp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comp_data', models.CharField(max_length=100)),
                ('comp_date', models.CharField(max_length=100)),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_address', models.CharField(max_length=100)),
                ('comp_phone', models.CharField(max_length=100)),
                ('comp_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
    ]
