# Generated by Django 4.2 on 2023-07-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_test_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact_list',
            fields=[
                ('cont_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cont_name', models.CharField(max_length=100)),
                ('cont_phone', models.CharField(max_length=100)),
                ('cont_email', models.CharField(max_length=100)),
                ('cont_date', models.CharField(max_length=100)),
                ('cont_time', models.CharField(max_length=100)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_organization')),
            ],
            options={
                'db_table': 'tbl_contact_list',
            },
        ),
    ]
