# Generated by Django 4.2 on 2023-07-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tbl_contact_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
    ]
